#!/usr/bin/env sh
APP_ID='dotfiles.andrewrabert.tmux-scratchpad'
TITLE='tmux'

ww-rs \
    --toggle \
    --center=initial \
    --filter "${APP_ID}" \
    -- ghostty --title="${TITLE}" --class="${APP_ID}" -e zsh -ic 'tmux-attach --prompt'
    #-- foot --title="${TITLE}" --app-id="${APP_ID}" -- zsh -ic 'tmux-attach --prompt'
