#!/usr/bin/env sh
APP_ID='obsidian'
exec ww-rs \
    --toggle \
    --center=initial \
    --filter "${APP_ID}" \
    --process-regex '^/app/obsidian\x00' \
    -- kioclient exec ~/.local/share/flatpak/exports/share/applications/md.obsidian.Obsidian.desktop
