#!/usr/bin/env python3
import argparse
import asyncio
import pathlib
import subprocess
import sys

CACHE_DIR = pathlib.Path("~/.cache/lgogdownloader").expanduser()
CONFIG_DIR = pathlib.Path("~/.dotfiles/private/lgogdownloader").expanduser()
GOG_DIR = pathlib.Path("/storage/Games/PC/GOG.com")
DEFAULT_IMAGE = "ghcr.io/andrewrabert/lgogdownloader"


def files_to_mtime(root):
    stack = [root]
    files = {}
    while stack:
        for path in stack.pop().iterdir():
            if path.is_dir():
                stack.append(path)
            elif path.is_file():
                files[str(path)] = path.stat().st_mtime
    return files


class LGOGDownloader:
    def __init__(self, image, pull=False):
        self.image = image
        self.pull = pull

    async def shell(self):
        return await self._run(shell=True)

    async def run(self):
        return await self._run()

    async def _run(self, *, shell=False):
        args = [
            "podman",
            "run",
            "--rm",
            "--name",
            "gog-update",
            "-e",
            "HOME",
            "-v",
            f"{GOG_DIR}:/downloads",
            "-v",
            f"{CACHE_DIR}:/cache",
            "-v",
            f"{CONFIG_DIR}:/config",
        ]
        if self.pull:
            args.append("--pull=always")
        if shell:
            args.append("-it")
        args.append(self.image)
        if shell:
            args.extend(["--", "sh", "-l"])

        proc = await asyncio.create_subprocess_exec(*args)
        await proc.wait()
        if proc.returncode != 0:
            raise subprocess.CalledProcessError(proc.returncode, args)


async def record_file_hashes():
    proc = await asyncio.create_subprocess_exec(
        "file-hash-recorder", str(GOG_DIR)
    )
    await proc.wait()
    if proc.returncode != 0:
        raise subprocess.CalledProcessError(
            proc.returncode, ["file-hash-recorder", str(GOG_DIR)]
        )


async def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--image", default=DEFAULT_IMAGE)
    parser.add_argument("--no-pull", action="store_true")
    parser.add_argument("--shell", action="store_true")
    args = parser.parse_args()

    lgogdownloader = LGOGDownloader(image=args.image, pull=not args.no_pull)

    if args.shell:
        await lgogdownloader.shell()
        sys.exit()
    else:
        CACHE_DIR.mkdir(parents=True, exist_ok=True)
        before = files_to_mtime(GOG_DIR)
        await lgogdownloader.run()
        after = files_to_mtime(GOG_DIR)

        for path in sorted(set([*before.keys(), *after.keys()])):
            try:
                before_mtime = before[path]
            except KeyError:
                print("New:", path)
                continue

            try:
                after_mtime = after[path]
            except KeyError:
                print("Deleted:", path)
                continue

            if before_mtime != after_mtime:
                print("Modified:", path)

        await record_file_hashes()


if __name__ == "__main__":
    asyncio.run(main())
