#!/usr/bin/env sh
set -e
exec harmonize --stdin << EOF
[harmonize]
source = "/storage/Audio/Library"
target = "/storage/Audio/Lossy_opus_128"
source_exclude = [
    "*.accurip",
    "*.auCDtect",
    "*.cue",
    "*.log",
    "*.nfo",
    "*.pdf",
    "*.txt",
]

[converters.audio]
command = ["ffmpeg", "-y", "-i", "{input}", "-c:a", "libopus", "-b:a", "128k", "{output}"]

[converters.image]
command = ["imgconvert", "--force", "-f", "jpeg", "--resize-mode", "shrink", "--width", "2560", "--height", "2560", "--output", "{output}", "{input}"]

[mappings]
".flac" = { converter = "audio", output_ext = ".opus" }
".mp3" = { converter = "audio", output_ext = ".opus" }
".png" = { converter = "image", output_ext = ".jpg" }
".jpg" = { converter = "image" }
EOF
