#!/usr/bin/env sh
set -e

update_server() {
    cd "$1"
    server="$(basename "$1")"
    echo "$server - syncing certs"
    just copy-certs-to-remote > /dev/null 2>&1
    echo "$server - updating and reloading Docker containers"
    just reload-remote > /dev/null 2>&1
    cd - > /dev/null
}

~/src/nullsum/ar/certs-nullsum.net/bin/renew_all.sh

update_server ~/src/nullsum/ar/www.nullsum.net
