#!/usr/bin/env zsh

# needed to fix interleaved log output
# https://github.com/wercker/stern/issues/96
export GOMAXPROCS=1

() {
    typeset -g WRAPPED_BIN=
    local self=${${(%):-%x}:A}
    local name=${self:t}
    local cand
    for cand in ${(f)"$(whence -ap $name)"}; do
        if [[ "${cand:A}" != "$self" ]]; then
            WRAPPED_BIN=$cand
            return
        fi
    done
    print -u2 "$name: not found on PATH"
    exit 127
}

exec "$WRAPPED_BIN" "$@"
