theme = "native"
icons = "awesome"

[[block]]
block = "battery"
driver = "upower"

[[block]]
block = "sound"
device_kind = "source"
max_vol = 100
on_click = "toggle-source-mute"

[[block]]
block = "sound"
device_kind = "sink"
max_vol = 100
on_click = "set-volume --toggle-mute"

[[block]]
block = "time"
interval = 30
format = "%F %R"
