
[theme]
theme = "native"

[icons]
icons = "awesome4"

[[block]]
block = "battery"
missing_format = ""

# Sony WH-1000XM4
[[block]]
block = "bluetooth"
mac = "F8:4E:17:93:84:67"
disconnected_format = ""

[[block]]
block = "sound"
device_kind = "source"
max_vol = 100
[[block.click]]
button = "left"
cmd = "toggle-source-mute"

[[block]]
block = "sound"
device_kind = "sink"
max_vol = 100
[[block.click]]
button = "left"
cmd = "set-volume --toggle-mute"

[[block]]
block = "net"
format = "$icon"

[[block]]
block = "time"
interval = 30
format = "$timestamp.datetime(f:'%Y-%m-%d %R')"
