
[theme]
theme = "native"

[icons]
icons = "awesome4"

[[block]]
block = "battery"
missing_format = ""

[[block]]
block = "sound"
device_kind = "source"
max_vol = 100

[[block]]
block = "sound"
device_kind = "sink"
max_vol = 100

[[block]]
block = "time"
interval = 30
format = "$timestamp.datetime(f:'%Y-%m-%d %R')"
