
[theme]
theme = "native"

[icons]
icons = "awesome4"

[[block]]
block = "battery"
missing_format = ""

[[block]]
block = "sound"
device_kind = "source"
max_vol = 100
[[block.click]]
button = "left"
cmd = "toggle-source-mute"

[[block]]
block = "sound"
device_kind = "sink"
max_vol = 100
[[block.click]]
button = "left"
cmd = "set-volume --toggle-mute"

[[block]]
block = "time"
interval = 30
format = "$timestamp.datetime(f:'%Y-%m-%d %R')"
