#!/usr/bin/env sh

# Single-instance enforcement
exec 9>/tmp/lounge-htpc-cli.lock
flock -n 9 || { echo "Another instance is already running" >&2; exit 1; }

http_request() {
    curl -X POST -v "http://127.0.0.1${1}"
}

is_power_off() {
    [ "$(curl -s http://127.0.0.1/status | jq -r .power)" = "off" ]
}

is_playing() {
    [ "$(playerctl status 2>/dev/null)" = "Playing" ]
}

power_off() {
    playerctl pause
    http_request /power/off
}

power_on() {
    http_request /power/on
    playerctl play
}

case "$1" in
    brightness-max)
        http_request /brightness/max
        ;;
    brightness-min)
        http_request /brightness/min
        ;;
    volume-up)
        http_request /volume/up
        ;;
    volume-down)
        http_request /volume/down
        ;;
    volume-mute-toggle)
        http_request /mute/toggle
        ;;
    power-off)
        power_off
        ;;
    power-on)
        power_on
        ;;
    power-toggle)
        if is_power_off; then
            power_on
        else
            power_off
        fi
        ;;
    *)
        echo 'usage: (brightness-min|brightness-max|power-toggle|power-on|power-off|volume-up|volume-down|volume-mute-toggle)' >&2
        exit 1
esac
