#!/usr/bin/env sh
set -e
ENVDIR="$1"
if ! [ -d "$ENVDIR" ]; then
    echo 'usage: VIRTUALENV' >&2
    exit 1
fi
ENVDIR="$(realpath "$ENVDIR")"
printf '. %s\n' "${ENVDIR}/bin/activate" > .envrc
direnv allow
