#!/usr/bin/env python
"""Show Python module filesystem paths"""

import argparse
import importlib.util


def main():
    parser = argparse.ArgumentParser("whpy", description=__doc__)
    parser.add_argument("module")
    args = parser.parse_args()

    spec = importlib.util.find_spec(args.module)
    if spec is None:
        parser.error("module not found")

    if spec.origin is None:
        parser.error("built-in module")

    path = spec.origin

    print(path)


if __name__ == "__main__":
    main()
