#!/usr/bin/env python3
import argparse
import pathlib


def all_files(*paths):
    stack = []
    files = set()
    for path in paths:
        if not path.exists():
            raise ValueError(f"path does not exist: {path}")
        elif path.is_file():
            files.add(path)
        elif path.is_dir():
            stack.append(path)
    while stack:
        for path in stack.pop().iterdir():
            if path.is_dir():
                stack.append(path)
            else:
                files.add(path)
    return sorted(files)


def _parser_path(value):
    path = pathlib.Path(value).absolute()
    obsidian_root = path / ".obsidian"
    if not obsidian_root.is_dir():
        raise ValueError
    return path


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("path", type=pathlib.Path)
    args = parser.parse_args()

    root_path = args.path
    obsidian_root = root_path / ".obsidian"
    obsidian_trash = root_path / ".trash"
    for path in all_files(root_path):
        if obsidian_root in path.parents:
            continue
        if obsidian_trash in path.parents:
            continue
        if path.suffix.lower() != ".md":
            continue
        contents = path.read_text()
        if not contents.strip():
            path.unlink()


if __name__ == "__main__":
    main()
