#!/usr/bin/env sh

if [ "$HOST_DOTFILES" != 'pikvm' ]; then
    exit
fi

BLUE='\033[0;34m'
RED='\033[0;31m'
NC='\033[0m'

printf "${BLUE}==> Updating all installed packages...${NC}\n"
pacman -Syu --noconfirm
echo ""

printf "${BLUE}==> Checking for foreign packages (not in repos)...${NC}\n"
pacman -Qm || true
echo ""

printf "${BLUE}==> Checking for packages with missing dependencies...${NC}\n"
pacman -Dk
echo ""

printf "${BLUE}==> Checking if all installed packages are cached...${NC}\n"
if ! pacman -Sp $(pacman -Qq) 2>/dev/null | grep -qv '^file://'; then
    printf "All packages cached\n"
else
    printf "${RED}Some packages not cached, downloading...${NC}\n"
    pacman -Sw --noconfirm $(pacman -Qq)
fi
echo ""

printf "${BLUE}==> Pruning pacman cache to only installed packages...${NC}\n"
paccache \
    --remove \
    --keep 1
echo ""

printf "${BLUE}==> Checking for .pacnew and .pacsave files...${NC}\n"
find /etc -regextype posix-extended -regex ".+\.pac(new|save)" 2> /dev/null || true
echo ""
