#!/usr/bin/env sh
set -e

show_help() {
    cat << EOF
usage:
    -f, --force     force installation
    --rustup-sh     install rustup via sh.rustup.rs even if pacman is present
    --help          show help and exit
EOF
}

FORCE=
RUSTUP_SH=
while [ $# -gt 0 ]; do
    case "$1" in
        -f|--force)
            FORCE=1
            shift
            ;;
        --rustup-sh)
            RUSTUP_SH=1
            shift
            ;;
        --help)
            show_help
            exit
            ;;
        *)
            echo 'error: unknown argument(s)' >&2
            exit 1
    esac
done

if [ -z "$FORCE" ] && ! command -v rustup > /dev/null; then
    exit
fi

if ! command -v rustup > /dev/null; then
    if [ -z "$RUSTUP_SH" ] && command -v pacman > /dev/null; then
        echo 'Installing rustup via pacman'
        sudo pacman -S --needed --noconfirm rustup
    else
        export CARGO_HOME="${HOME}/.cargo"

        cleanup() {
            rm -f "${TEMP_FILE}"
        }
        trap cleanup EXIT
        TEMP_FILE="$(mktemp)"

        URL='https://sh.rustup.rs'
        printf 'Installing rustup from %s\n' "${URL}"
        curl "${URL}" > "${TEMP_FILE}"
        chmod +x "${TEMP_FILE}"
        RUSTUP_INIT_SKIP_PATH_CHECK=yes "${TEMP_FILE}" -y --no-modify-path

        echo 'Successfully installed rustup'
        export PATH="${CARGO_HOME}/bin:${PATH}"
    fi
fi

if ! rustup toolchain list | grep -q '^stable-'; then
    echo 'Installing toolchain: stable'
    rustup toolchain install stable
fi
if ! rustup component list --installed | grep -q '^rust-analyzer-'; then
    echo 'Installing component: rust-analyzer'
    rustup component add rust-analyzer
fi
rustup update
