#!/usr/bin/env sh
set -e

if command -v uv >/dev/null; then
    echo "Upgrading all uv tool installs..."
    uv tool upgrade --all

    echo "Updating uv PEP 723 scripts in dotfiles..."
    uv-update-all "${DOTFILES}/.bin"
fi
