#!/usr/bin/env sh
set -e
XDG_DATA_DIR="${XDG_DATA_DIR:-$HOME/.local/share}"
BASE_DIR="${XDG_DATA_DIR}/tinted-theming"

mkdir -p "${BASE_DIR}"

for repo in tinted-shell; do
    repo_dir="${BASE_DIR}/${repo}"
    if ! [ -d "${repo_dir}" ]; then
        git clone "https://github.com/tinted-theming/${repo}" "${repo_dir}" > /dev/null
    else
        cd "${repo_dir}"
        git clean -xdff
        git pull -q
    fi
done
SHELL_DIR="${BASE_DIR}/tinted-shell"
BASE16_DIR="${XDG_DATA_DIR}/base16-shell"
if [ "$(realpath "${BASE16_DIR}")" != "${SHELL_DIR}" ]; then
    rm -rf "${BASE16_DIR}"
    ln -sT "${SHELL_DIR}" "${BASE16_DIR}"
fi

