#!/usr/bin/env sh
set -e

if [ "$(uname -s)" = "Darwin" ]; then
    exit
fi

# mac (arm) seems to have bugs with heredocs occasionally
# returning empty
if ! command -v dash > /dev/null; then
    exit
fi

actual="$(realpath "$(command -v dash)")"
if [ "$actual" = "$(realpath ~/.local/bin/sh)" ]; then
    exit
fi

mkdir -p ~/.local/bin
ln -sf "$actual" ~/.local/bin/sh
