#!/usr/bin/env python3
import json
import pathlib
import shutil

if shutil.which("discord"):
    path = pathlib.Path("~/.config/discord/settings.json").expanduser()
    if path.exists():
        settings = json.loads(path.read_text())
        if not settings.get("SKIP_HOST_UPDATE"):
            settings["SKIP_HOST_UPDATE"] = True
            path.write_text(json.dumps(settings))
