#!/usr/bin/env sh
set -eu

SOURCE="${DOTFILES}/ghostty"

case "$(uname -s)" in
    Darwin) TARGET=~/Library/Application\ Support/com.mitchellh.ghostty ;;
    *)      TARGET=~/.config/ghostty ;;
esac

case "$(uname -s)" in
    Darwin)
        if ! [ -d /Applications/Ghostty.app ]; then
            rm -rf "${TARGET}"
            exit
        fi
        ;;
    *)
        if ! command -v ghostty > /dev/null; then
            rm -rf "${TARGET}"
            exit
        fi
        ;;
esac

if [ "$(realpath "${TARGET}")" != "${SOURCE}" ]; then
    echo 'Linking configuration ...'
    rm -rf "${TARGET}"
    ln -sfn "${SOURCE}" "${TARGET}"
fi

CONFIG_LOCAL="${SOURCE}/config-local"
case "$(uname -s)" in
    Darwin)
        printf 'config-file = config-macos\n' > "${CONFIG_LOCAL}"
        ;;
    *)
        rm -f "${CONFIG_LOCAL}"
        ;;
esac
