#!/usr/bin/env python3
import asyncio
import os
import pathlib
import shutil
import subprocess

HOSTNAME = os.environ["HOST_DOTFILES"]

HOME = pathlib.Path("~").expanduser()
CONFIG = HOME / ".config"
LOCAL_SHARE = HOME / ".local" / "share"

DOTFILES = pathlib.Path(os.environ["DOTFILES"])

if DOTFILES_PRIVATE := os.environ.get("DOTFILES_PRIVATE", None):
    DOTFILES_PRIVATE = pathlib.Path(DOTFILES_PRIVATE)

LINKS = {
    LOCAL_SHARE / "icons": DOTFILES / "kde" / "icons",
    LOCAL_SHARE / "applications": DOTFILES / "kde" / "applications",
    LOCAL_SHARE / "kwin": DOTFILES / "kde" / "kwin",
}

if DOTFILES_PRIVATE is not None:
    LINKS.update(
        {
            LOCAL_SHARE / "kf6" / "searchproviders": DOTFILES_PRIVATE
            / "kde"
            / "searchproviders",
        }
    )


match HOSTNAME:
    case "mars":
        LINKS.update(
            {
                CONFIG / "autostart": DOTFILES / "kde" / "autostart" / "mars",
            }
        )
    case "phobos":
        LINKS.update(
            {
                CONFIG / "autostart": DOTFILES
                / "kde"
                / "autostart"
                / "phobos",
            }
        )


def delete(path):
    if path.is_symlink() or path.is_file():
        path.unlink(missing_ok=True)
    elif path.is_dir():
        shutil.rmtree(path)


def is_linked(source, target):
    return source.is_symlink() and source.readlink() == target


def symlink(source, target):
    if not is_linked(source, target):
        delete(source)
        source.parent.mkdir(exist_ok=True, parents=True)
        source.symlink_to(target)


class Rsync:
    @staticmethod
    async def copy_into_replace_contents(source, target):
        target.mkdir(exist_ok=True, parents=True)
        proc = await asyncio.create_subprocess_exec(
            "rsync", "-avq", "--delete", f"{source}/", str(target)
        )
        await proc.wait()
        if proc.returncode != 0:
            raise subprocess.CalledProcessError(proc.returncode, "rsync")

    @staticmethod
    async def copy_replace(source, target):
        target.parent.mkdir(exist_ok=True, parents=True)
        proc = await asyncio.create_subprocess_exec(
            "rsync", "-avq", str(source), str(target)
        )
        await proc.wait()
        if proc.returncode != 0:
            raise subprocess.CalledProcessError(proc.returncode, "rsync")


async def update_desktop_database():
    proc = await asyncio.create_subprocess_exec("update-desktop-database")
    await proc.wait()
    if proc.returncode != 0:
        raise subprocess.CalledProcessError(
            proc.returncode, "update-desktop-database"
        )


class KWriteConfig:
    @staticmethod
    async def write(
        *,
        delete=False,
        file=None,
        group=None,
        key=None,
        notify=False,
        value_type=None,
        value=None,
    ):
        args = ["kwriteconfig6"]
        if file is not None:
            args.extend(("--file", file))
        if group is not None:
            args.extend(("--group", group))
        if key is not None:
            args.extend(("--key", key))
        if value_type is not None:
            args.extend(("--type", value_type))
        if delete:
            args.append("--delete")
        if notify:
            args.append("--notify")
        if not delete and value:
            args.append(value)
        if value is not None:
            args.append(value)
        proc = await asyncio.create_subprocess_exec(*args)
        await proc.wait()
        if proc.returncode != 0:
            raise subprocess.CalledProcessError(
                proc.returncode, "kwriteconfig6"
            )


async def configure_kde():
    settings = {
        "kdesurc": {
            "super-user-command": {
                "super-user-command": "sudo",
            }
        },
        "kuriikwsfilterrc": {
            "General": {
                "DefaultWebShortcut": "google",
                "EnableWebShortcuts": "true",
                "KeywordDelimiter": ":",
                "UsePreferredWebShortcutsOnly": "false",
            }
        },
        "dolphinrc": {
            "KDE": {"AnimationDurationFactor": "0"},
            "MainWindow": {"MenuBar": "Disabled"},
            "General": {
                "OpenNewTabAfterLastTab": "true",
                "ShowFullPath": "true",
            },
        },
    }
    for file, groups in settings.items():
        for group, keys in groups.items():
            for key, value in keys.items():
                await KWriteConfig.write(
                    file=file,
                    group=group,
                    key=key,
                    value=value,
                    notify=True,
                )


async def main():
    if not shutil.which("plasmashell"):
        exit()

    for target, source in LINKS.items():
        symlink(target, source)

    if HOSTNAME:
        source = DOTFILES / "kde" / "applications_host" / HOSTNAME
        target = LOCAL_SHARE / "applications" / "dotfiles-localhost"
        if source.exists():
            await Rsync.copy_into_replace_contents(source, target)
        else:
            delete(target)

    if HOSTNAME in ("mars", "phobos"):
        await update_desktop_database()

    await configure_kde()


if __name__ == "__main__":
    asyncio.run(main())
