#!/usr/bin/env sh
set -e

if ! command -v nvim > /dev/null; then
    rm -rf ~/.config/nvim ~/.cache/nvim ~/.local/share/nvim
    exit
fi

if [ "$(realpath ~/.config/nvim)" != "$DOTFILES/nvim" ]; then
    rm -rf ~/.config/nvim
    ln -sT "${DOTFILES}/nvim" ~/.config/nvim
fi

# skip plugin sync if lazy is disabled
if ! [ -e ~/.config/nvim/lazy.disable ]; then
    nvim --headless "+Lazy! sync" +TSUpdateSync +qa
    # workaround lazy.nvim output not ending with a new line
    echo
fi
