#!/usr/bin/env sh
set -eu

if ! command -v vicinae > /dev/null; then
    rm -rf ~/.config/vicinae
else
    if [ "$(realpath ~/.config/vicinae)" != "${DOTFILES}/vicinae" ]; then
        echo "Linking configuration ..."
        rm -rf ~/.config/vicinae
        ln -s "${DOTFILES}/vicinae" ~/.config/vicinae
    fi
fi
