#!/usr/bin/env sh
set -e

if ! command -v wezterm > /dev/null; then
    rm -rf ~/.config/wezterm
    exit
fi

if [ "$(realpath ~/.config/wezterm 2> /dev/null)" != "$DOTFILES/wezterm" ]; then
    echo 'Linking configuration ...'
    rm -rf ~/.config/wezterm
    mkdir -p ~/.config
    ln -sT "${DOTFILES}/wezterm" ~/.config/wezterm
fi
