#!/usr/bin/env sh
set -eu

case "${HOST_DOTFILES}" in
    aweber|mars|sol|phobos)
        SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
        "${SCRIPT_DIR}/.60-zoekt-simple"
        ;;
    *)
        rm -rf "${DOTFILES}/.local/zoekt-simple"
        ;;
esac
