#!/usr/bin/env sh
set -e

if ! command -v zeditor > /dev/null && ! [ -e /Applications/Zed.app/ ]; then
    rm -rf ~/.config/zed
    exit
fi

if [ "$(realpath ~/.config/zed)" != "$DOTFILES/zed" ]; then
    rm -rf ~/.config/zed
    ln -sT "${DOTFILES}/zed" ~/.config/zed
fi
