#!/usr/bin/env sh
set -eu

case "${HOST_DOTFILES}" in
    aweber)
        exec "${DOTFILES}/full-update/.py-dotfiles" zoekt-simple
        ;;
    *)
        rm -rf "${DOTFILES}/.local/zoekt-simple"
        ;;
esac
