#!/usr/bin/env python3
import asyncio
import os
import subprocess


async def is_unit_enabled(name, user=False):
    args = [
        "systemctl",
        "--user" if user else "--system",
        "show",
        "--property=UnitFileState",
        "--",
        name,
    ]
    proc = await asyncio.create_subprocess_exec(
        *args,
        stdout=asyncio.subprocess.PIPE,
    )
    stdout, _ = await proc.communicate()
    if proc.returncode != 0:
        raise subprocess.CalledProcessError(proc.returncode, args)
    match stdout.decode().strip():
        case "UnitFileState=enabled":
            return True
        case "UnitFileState=disabled":
            return False
        case _:
            raise RuntimeError


async def enable_unit(name, now=False, user=False):
    if await is_unit_enabled(name, user=user):
        return
    print(f"Enabling unit {name} (user={user})")
    args = []
    if not user:
        args.append("sudo")

    args.extend(
        [
            "systemctl",
            "--user" if user else "--system",
            "enable",
        ]
    )
    if now:
        args.append("--now")
    args.extend(["--", name])
    proc = await asyncio.create_subprocess_exec(*args)
    await proc.communicate()
    if proc.returncode != 0:
        raise subprocess.CalledProcessError(proc.returncode, args)


async def main():
    if os.environ["HOST_DOTFILES"] != "mars":
        return

    await enable_unit("syncthing", user=True)


if __name__ == "__main__":
    asyncio.run(main())
