#!/usr/bin/env sh
set -e 
if [ "$HOST_DOTFILES" != 'sol' ]; then
    exit
fi

if ! command uv > /dev/null; then
    full-update 35-uv --force
fi
exec "${DOTFILES}/scripts/install-jellium-desktop-nightly" flatpak
