hide-soft-keyboard-on-startup = false
soft-keyboard-toggle-behavior = disable
bell-character = ignore
terminal-toolbar-height = 0.8
volume-keys = volume
extra-keys = [ \
 [ \
     {key: 'ESC'}, \
     {key: 'TAB', popup: {macro: "SHIFT TAB", display: "shift+tab"}}, \
     {key: '~'}, \
     {key: '-'}, \
     {key: DRAWER, popup: {macro: "KEYBOARD", display: "keyboard"}}, \
     {key: 'UP'}, \
     {key: 'BACKSLASH'}, \
     {key: '/'} \
 ], \
 [ \
     {key: 'SHIFT'}, \
     {key: 'CTRL'}, \
     {key: 'ALT'}, \
     {key: 'DEL'}, \
     {key: 'LEFT'}, \
     {key: 'DOWN'}, \
     {key: 'RIGHT'}, \
     {key: ':'} \
 ] \
]
