#!/usr/bin/env python3
import argparse

parser = argparse.ArgumentParser()
parser.add_argument("hex")
args = parser.parse_args()

length = 4 * len(args.hex)
fmt = "{:0" + str(length) + "b}"
print(fmt.format(int(args.hex, 16)))
