#!/usr/bin/env sh
case "$1" in
    copy|paste)
        MODE="$1"
        ;;
    *)
        case "$0" in
            *copy)
                MODE='copy'
                ;;
            *paste)
                MODE='paste'
                ;;
        esac
        if [ -z "$MODE" ]; then
            echo 'usage: clipboard (copy|paste)'
            exit 1
        fi
esac

clipboard_macos() {
    if command -v pbcopy > /dev/null; then
        case "$MODE" in
            copy)
                pbcopy
                ;;
            paste)
                pbpaste
                ;;
        esac
    else
        return 1
    fi
}

clipboard_wayland() {
    if [ -n "$WAYLAND_DISPLAY" ]; then
        case "$MODE" in
            copy)
                wl-copy
                ;;
            paste)
                wl-paste
                ;;
        esac
    else
        return 1
    fi
}


clipboard_tmux() {
    if [ -n "$TMUX" ]; then
        case "$MODE" in
            copy)
                tmux load-buffer -w -
                ;;
            paste)
                tmux refresh-client -l
                sleep 0.1
                tmux save-buffer -
                ;;
        esac
    else
        return 1
    fi
}


clipboard_termux() {
    if command -v termux-clipboard-get > /dev/null; then
        case "$MODE" in
            copy)
                termux-clipboard-set
                ;;
            paste)
                termux-clipboard-get
                ;;
        esac
    else
        return 1
    fi
}

clipboard_termux \
    || clipboard_wayland \
    || clipboard_termux \
    || clipboard_macos \
    || clipboard_tmux \
    || (echo error: no suitable clipboard command detected >&2; exit 1)
