#!/bin/sh
while true; do 
    START="$(date +%s)"
    obsidian
    END="$(date +%s)"
    if [ "${START}" = "${END}" ]; then
        echo 'warning: application exited immediately' >&2
        sleep 1
    fi
done
