#!/usr/bin/env -S uv run --script
"""
FFmpeg duplicate frame removal tool with async processing.

# /// script
# dependencies = [
#     "async_executor",
# ]
# ///
"""

import argparse
import asyncio
import json
import pathlib
import tempfile

import async_executor


class ffprobe:
    class ProcessError(Exception):
        """Raised when ffprobe fails to run"""

    @classmethod
    async def stream_info(cls, path):
        proc = await asyncio.create_subprocess_exec(
            "ffprobe",
            "-v",
            "error",
            "-show_streams",
            "-print_format",
            "json",
            "--",
            str(path),
            stdout=asyncio.subprocess.PIPE,
        )
        stdout, _ = await proc.communicate()
        if proc.returncode != 0:
            raise cls.ProcessError
        return json.loads(stdout)["streams"]


class ffmpeg:
    class ProcessError(Exception):
        """Raised when ffprobe fails to run"""

    @classmethod
    async def remove_duplicates(cls, source, target, avg_frame_rate):
        proc = await asyncio.create_subprocess_exec(
            "ffmpeg",
            "-i",
            source,
            "-vf",
            f"mpdecimate,setpts=N/{round(avg_frame_rate, 3)}/TB",
            target,
            stdout=asyncio.subprocess.DEVNULL,
            stderr=asyncio.subprocess.DEVNULL,
        )
        await proc.communicate()
        if proc.returncode != 0:
            raise cls.ProcessError

    @classmethod
    async def frame_hashes(cls, path):
        proc = await asyncio.create_subprocess_exec(
            "ffmpeg",
            "-i",
            str(path),
            "-an",
            "-f",
            "framemd5",
            "-",
            stdout=asyncio.subprocess.PIPE,
            stderr=asyncio.subprocess.DEVNULL,
        )
        stdout, _ = await proc.communicate()
        if proc.returncode != 0:
            raise cls.ProcessError
        hashes = []
        for line in stdout.decode().splitlines():
            if line.startswith("#") or not line.strip():
                continue
            hashes.append(line.split(",")[-1].strip())
        return hashes

    @classmethod
    async def remove_duplicates_above(
        cls, source, target, avg_frame_rate, max_dupes
    ):
        hashes = await cls.frame_hashes(source)
        drop_ranges = _find_drop_ranges(hashes, max_dupes)
        if not drop_ranges:
            return False
        between_exprs = "+".join(
            f"between(n,{start},{end})" for start, end in drop_ranges
        )
        vf = f"select='not({between_exprs})',setpts=N/{round(avg_frame_rate, 3)}/TB"
        proc = await asyncio.create_subprocess_exec(
            "ffmpeg",
            "-i",
            str(source),
            "-vf",
            vf,
            str(target),
            stdout=asyncio.subprocess.DEVNULL,
            stderr=asyncio.subprocess.DEVNULL,
        )
        await proc.communicate()
        if proc.returncode != 0:
            raise cls.ProcessError
        return True


def _find_drop_ranges(hashes, max_dupes):
    ranges = []
    i = 0
    while i < len(hashes):
        j = i + 1
        while j < len(hashes) and hashes[j] == hashes[i]:
            j += 1
        if j - i > max_dupes:
            ranges.append((i + max_dupes, j - 1))
        i = j
    return ranges


async def _process_path(path, max_dupes):
    info = await ffprobe.stream_info(path)
    print(json.dumps(info, indent=2, sort_keys=True))

    avg_frame_rate = None
    for stream in info:
        avg_frame_rate = stream.get("avg_frame_rate")
        if avg_frame_rate:
            x, y = avg_frame_rate.split("/")
            if x and y:
                avg_frame_rate = int(x) / int(y)
                break

    if not avg_frame_rate:
        raise RuntimeError

    with tempfile.NamedTemporaryFile(
        dir=path.parent, suffix=path.suffix
    ) as tmpfile:
        tmpfile = pathlib.Path(tmpfile.name)
        tmpfile.unlink()
        if max_dupes > 0:
            changed = await ffmpeg.remove_duplicates_above(
                path, tmpfile, avg_frame_rate, max_dupes
            )
            if not changed:
                tmpfile.touch()
                return
        else:
            await ffmpeg.remove_duplicates(path, tmpfile, avg_frame_rate)
        tmpfile.replace(path)
        tmpfile.touch()


async def main():
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "-n",
        metavar="NUM",
        dest="num_procs",
        type=int,
        default=1,
        help="number of parallel jobs (default: %(default)s)",
    )
    parser.add_argument(
        "-d",
        "--max-dupes",
        metavar="NUM",
        type=int,
        default=0,
        help="allow up to NUM consecutive duplicate frames (default: %(default)s, remove all)",
    )
    parser.add_argument("path", type=pathlib.Path, nargs="+")
    args = parser.parse_args()

    executor = async_executor.AsyncExecutor(args.num_procs)
    for path in args.path:
        executor.submit(_process_path, path, args.max_dupes)

    async for result in executor:
        result.result()


if __name__ == "__main__":
    asyncio.run(main())
