#!/usr/bin/env sh
set -e
cd ~/src/github/comfyanonymous/comfyui || exit 1

uv pip install --upgrade --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/rocm7.1
uv pip install --upgrade -r requirements.txt

# some custom nodes call python -m pip directly
uv pip install pip

# uv run had issues
. ./.venv/bin/activate
exec ./.venv/bin/python main.py --listen 0.0.0.0
