#!/usr/bin/env sh
set -e
cd ~/src/github/comfyanonymous/comfyui || exit 1

# 2025-05-12 fixes miopen-hip >= 6.3.3
#export MIOPEN_FIND_MODE=1

# 2025-05-12 maybe needed when miopen-hip permission issues
#export MIOPEN_DISABLE_CACHE=1

# 2025-11-14 installing the prebuilts this way is more reliable than Arch Linux packages
#uv pip install --upgrade --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/rocm7.0

exec ./.venv/bin/python main.py --listen 0.0.0.0
