#!/usr/bin/env sh
set -eu

if [ -t 0 ] && [ $# -ne 1 ]; then
    echo "usage: PROMPT" >&2
    exit 1
fi

exec claude \
    --output-format=text \
    --tools='' \
    --no-session-persistence \
    --print \
    -- "$@"
